---

- name: Creates directory 
  file:
    path: ~/web
    state: directory

- name: Copy files to ec2 instance
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/web
    
- name: extract zip artifat into ec2 instance
  unarchive:
    src: ~/web/artifact.tar.gz
    dest: ~/web
    remote_src: yes

- name: Extract file and start server
  become: true
  shell:
    cmd: |
      cd web
      npm install
      pm2 stop default
      pm2 start npm -- start